[package]
name = "module-loader"
version = "0.12.3"
authors = ["K. <kayo@illumium.org>"]
edition = "2018"
publish = false

[dependencies.rquickjs]
package = "quickjs-jit"
path = "../.."
default-features = false
features = ["futures", "rust-alloc", "loader", "dyn-load", "std"]

[features]
default = ["macro"]
macro = ["rquickjs/macro"]
